version: '3'

services:
  postgres:
    image: postgres:11
    #    user: ${CURRENT_UID}
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passwd
    volumes:
      - ./postgres:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - postgres
    volumes:
      - ./../backend/:/opt/backend
