version: '3'

services:
  postgres:
    image: postgres:11
    #    user: ${CURRENT_UID}
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passwd
    volumes:
      - ./postgres:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "localhost"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - postgres
      - rabbitmq
    image: news_api
    volumes:
      - ./../news/:/opt/news
