# Generated by Django 2.2.4 on 2020-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=75)),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
